newprintpress15/material/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('addMsupplier/', views.addMsupplier, name='add-Msupplier'),
    path('Morder/', views.Morder, name='MOrder-place'),
    path('allMorders/', views.allMorders, name="all-Morders"),
    path('Mpayment/', views.Mpayment, name="Mpayment-form"),
    path('Minvoice', views.Invoicepage,name="Minvoice"),
]

newprintpress15/newprintpress/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    # path('', auth_views.LoginView.as_view()),

    path('admin/', admin.site.urls),
    path('login/', include('django.contrib.auth.urls')),
    path('',include('printapp.urls')),
    path('',include('material.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newprintpress15/material/models.py
from datetime import datetime
from django.db import models

class Msupplier(models.Model):
    Name = models.CharField(max_length=30)
    Company = models.CharField(max_length=30)
    Mobile = models.CharField(max_length=12)
    Address = models.TextField(blank=True)

    def __str__(self):
        return self.Name

class MOrder(models.Model):
    supplierName = models.ForeignKey(Msupplier, on_delete=models.CASCADE)
    OrderName = models.CharField(max_length=30)
    Date = models.DateField(default = datetime.now)
    Size = models.CharField(max_length=30,blank=True)
    gsm = models.IntegerField(blank=True)
    Quantity =models.CharField(max_length=30)
    Amount =models. IntegerField()
    Comment =models.TextField(blank=True)

    def __str__(self):
        return self.Mname

Paid_CHOICES = [
    ('Cash', 'Cash'),
    ('cheque', 'Cheque'),
    ('Online', 'Online'),
]


class MPayment(models.Model):
    Msupplier = models.ForeignKey(Msupplier,on_delete=models.CASCADE)
    Date = models.DateField(default = datetime.now)
    paidBy = models.CharField(max_length=10,choices=Paid_CHOICES,default='Cash')
    Amount = models.IntegerField(default=0)
    # Amount = models.IntegerField(default=0,blank=True)
    Comment = models.TextField(blank=True)

newprintpress15/printapp/models.py
from django.db import models
from datetime import datetime

class supplier(models.Model):
    Name = models.CharField(max_length=30)
    Company = models.CharField(max_length=30)
    Email = models.EmailField(max_length=254,blank=True,null=True)
    Mobile = models.IntegerField()
    Address = models.TextField(blank=True)


    def __str__(self):
        return self.Name

    # def __str__(self):
    #     return "%s %s" % (self.Name, self.Email)


class Order(models.Model):
    supplierName = models.ForeignKey(supplier, on_delete=models.CASCADE)
    OrderName = models.CharField(max_length=30)
    Date = models.DateField(default = datetime.now)
    document = models.FileField()
    Size = models.CharField(max_length=30)
    gsm = models.IntegerField()
    Quantity =models.IntegerField()
    Amount =models. IntegerField()
    Comment =models.TextField(blank=True)

    def __str__(self):
        return self.OrderName


Paid_CHOICES = [
    ('Cash', 'Cash'),
    ('cheque', 'Cheque'),
    ('Online', 'Online'),


]

class Payment(models.Model):
    supplierName = models.ForeignKey(supplier,on_delete=models.CASCADE)
    Date = models.DateField(default = datetime.now)
    paidIn = models.CharField(max_length=10,choices=Paid_CHOICES,default='Cash')
    credit = models.IntegerField(default=0)
    # Amount = models.IntegerField(default=0,blank=True)
    Comment = models.TextField(blank=True)


class Balance(models.Model):
    supplierName = models.ForeignKey(supplier,on_delete=models.CASCADE)
    # orderid = models.ForeignKey(Order,on_delete=models.CASCADE)
    # paymentid = models.ForeignKey(Payment,on_delete=models.CASCADE)
    Date = models.DateField(default = datetime.now)
    debit = models.IntegerField(default=0)
    credit = models.IntegerField(default=0)
    Amount = models.IntegerField(default=0,blank=True)

class attachments(models.Model):
    order =models.ForeignKey(Order,on_delete=models.CASCADE)
    files = models.FileField()

    # def __str__(self):
    #     return self.files

# Not yet used, testing purpose 
class Mails(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=1000)
    message = models.CharField(max_length=20000)
    document = models.FileField(upload_to='documents/')
    def __str__(self):
        return self.email

newprintpress15/templates/Allpayment.html
{% extends 'base.html' %}
{% block content %}
{% load humanize %}
{% load widget_tweaks %}
<br>
<!--payment filters-->
<div class="row">
    <div class="col">
        <div class="card card-body mr-3 ml-3">

            <form method="get">
                <div class="well">
                    <h4 style="margin-top: 0">Payment Filter</h4>
                    <hr>

                    <div class="row">
                        <div class="form-group col-sm-2 col-md-2">
                            <h6 class="mb-2">Supplier Name :</h6>
                            {% render_field filter2.form.supplierName class="form-control" %}
                        </div>
                        <div class="form-group col-sm-2 col-md-2">
                            <h6 class="mb-2">Paid By :</h6>
                            {% render_field filter2.form.paidIn class="form-control"  %}
                        </div>
                        <div class="form-group col-sm-2 col-md-2">
                            <h6 class="mb-2">Date :</h6>
                            {% render_field filter2.form.Date class="form-control" type="date" %}
                        </div>
                        <div class="form-group col-sm-2 col-md-2">
                            <h6 class="mb-2">To:</h6>
                            {% render_field filter2.form.start_date class="form-control" type="date" %}
                        </div>
                        <div class="form-group col-sm-2 col-md-2">
                            <h6 class="mb-2">From:</h6>
                            {% render_field filter2.form.end_date class="form-control" type="date" %}
                        </div>
                        <div class="form-group col-sm-2 col-md-2">
                            <h6 class="mb-2">Amount :</h6>
                            {% render_field filter2.form.credit class="form-control" %}
                        </div>
                        <div class="form-group col-sm-12 float-right ">
                            <button type="submit" class="btn btn-primary float-right"><i class="fas fa-search"></i>
                                Search
                            </button>
                        </div>

                    </div>
                </div>
            </form>
        </div>


        <!-- end of payment filters       -->
        <!--payment table-->

        <div class="card  mx-3 my-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="table table-hover table-responsive">
                            <div class="row">
                                <div class="col">
                                    <h3 class="card-title">Payment Details</h3>

                                </div>
                                <div class="col">
                                    <h3 class="float-right"><a href="{% url 'payment-form'%}" style="color:#DC7633"><i
                                            class="fas fa-plus-circle"></i></a></h3>

                                </div>
                            </div>
                            <hr>


                            <table class="table">
                                <thead class="thead-dark">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Service provider</th>
                                    <th scope="col">Payment Date</th>
                                    <th scope="col">Paid By</th>

                                    <th scope="col"> Amount</th>
                                    <th scope="col"> Comment</th>
                                    <th scope="col"> Cancel</th>


                                </tr>
                                </thead>
                                <tbody>

                                {% for i in filter2.qs %}
                                <tr>
                                    <th scope="row">{{forloop.counter}}</th>
                                    <td>{{i.supplierName}}</td>
                                    <td>{{i.Date}}</td>
                                    <td>{{i.paidIn}}</td>

                                    <td>{{i.credit|intcomma}}</td>
                                    <td>{{i.Comment}}</td>
                                    <td>
                                    <a href="{% url 'delete-payment' i.id %}" class="btn btn-danger mr-2" >Delete</a>
                                    </td> 


                                </tr>
              
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--end of payment table -->

{% endblock %}

newprintpress15/templates/MOrderform.html
{% extends 'base.html'%}
{% block content %}
{% load bootstrap4 %}
{% load widget_tweaks %}

{% load static %}
<div class="card  mx-3 my-3">

    <div class="card-body ">
        <h4 class="card-title">Place Order </h4>
        <hr>
        <div class="row">
            <div class="col">

                <img class="img-fluid" alt="Responsive image" src="{% static 'img/22562.jpg'%}"
                     style="width:500px;height:450px">
            </div>
            <div class="col">

                <form method="post" enctype="multipart/form-data" class="needs-validation" onsubmit="validatepassword()"
                      novalidate>
                    {% csrf_token %}
                    <div class="form-group"><label for="id_supplierName">Service provider</label>
                    {% render_field form.supplierName class="form-control"  id="id_supplierName"  %}
                    </div>
<div class="form-group">
<label for="id_OrderName">Order Name</label>
{% render_field form.OrderName class="form-control"  id="id_OrderName"  %}
</div>
<div class="form-group">
<label for="id_Date">Date :</label>
{% render_field form.Date class="form-control" type="Date" name="Date"  id="id_Date"  %}
</div>
<div class="form-group"><label for="id_Size">Size</label><input type="text" name="Size" maxlength="30" class="form-control" placeholder="Size" title="" required id="id_Size"></div>
<div class="form-group">
<label for="id_Date">GSM :</label>
{% render_field form.gsm class="form-control"  %}
</div>
<div class="form-group"><label for="id_Quantity">Quantity</label><input type="number" name="Quantity" class="form-control" placeholder="Quantity" title="" required id="id_Quantity"></div>
<div class="form-group"><label for="id_Amount">Amount</label><input type="number" name="Amount" class="form-control" placeholder="Amount" title="" required id="id_Amount"></div>
<div class="form-group"><label for="id_Comment">Comment</label><textarea name="Comment" cols="40" rows="3" class="form-control" placeholder="Comment" title="" id="id_Comment">
</textarea></div>
                    <button type="submit" class="btn btn-success">Order Place</button>
                </form>
            </div>
        </div>
    </div>
    <script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();

    </script>

    {% endblock content %}

newprintpress15/templates/Minvoicefilter.html
{% extends 'base.html'%}
{% block content %}
{% load widget_tweaks %}
<div class="container">
<form method="POST" >
    {%csrf_token%}
    <div class="well">
      <h3 style="margin-top: 5%">Invoice</h3>
        <br>
      <div class="message">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{message.tags}}!</strong> {% if message.tags %}{{ message}}"{% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}

            {% endif %}
        </div>
        <div class="row">
        <div class="form-group col-sm-3 col-md-3">
          <h6 class="mb-2">Supplier Name :</h6>
          {% render_field filter.form.supplierName class="form-control" %}
        </div>
        <div class="form-group col-sm-3 col-md-3">
                        <h6 class="mb-2">Date:</h6>
                        {% render_field filter.form.Date class="form-control" type="date"  %}
                    </div>
        <div class="form-group col-sm-3 col-md-3">
                        <h6 class="mb-2">Date From:</h6>
                       <input type="date" name="Datefrom" class="form-control" id="Date">

                        {% comment %} {% render_field filter.form.start_date class="form-control"  type="date"  %} {% endcomment %}
                    </div>
            <div class="form-group col-sm-3 col-md-3">
                        <h6 class="mb-2">Date To:</h6>
                        <input type="date" name="Dateto" class="form-control" id="id_end_date">
                        {% comment %} {% render_field filter.form.end_date class="form-control" type="date"  %} {% endcomment %}
                    </div>

      <div class="form-group col-sm-12  ">
          <button type="submit" class="btn btn-primary mt-4 float-right " ><i class="fas fa-search"></i> Search</button>
      </div>

		</div>
	</div>
    </form>

</div>
</div>
{% endblock %}

newprintpress15/templates/Order.html
{% extends 'base.html'%}
{% block content %}
<div class="mt-4"></div>
<div class="container ">
    <div class="card responsive">
        <div class="card-body mx-4 my-4">
            <h4 class="card-title">Order Details</h4>
            <hr>
            <form>
                <div class="form-group row">
                    <label for="name10" class="col-sm-2 col-form-label">Client Name</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="clientInputEmail1" value="{{supplier1.Name}}"
                               readonly>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="clinetInputEmail1" class="col-sm-2 col-form-label">Client Email address</label>
                    <div class="col-sm-8">
                        <input type="email" class="form-control" id="clientInputEmail1" value="{{supplier1.Email}}"
                               readonly>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="ordern" class="col-sm-2 col-form-label">Order Name</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="ordern">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="date1" class="col-sm-2 col-form-label">Date</label>
                    <div class="col-sm-8">
                        <input type="date" class="form-control" id="date1">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="size1" class="col-sm-2 col-form-label">Size</label>
                    <div class="col-sm-2">
                        <input type="text" class="form-control" id="size1">
                    </div>
                    <label for="Q1" class="col-sm-1 col-form-label">Qty</label>
                    <div class="col-sm-2">
                        <input type="number" class="form-control" id="Q1">
                    </div>
                    <label for="P1" class="col-sm-1 col-form-label">Price</label>
                    <div class="col-sm-2">
                        <input type="number" class="form-control" id="P1">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputamount" class="col-sm-2 col-form-label">Attachment</label>
                    <div class="col-sm-8">
                        <input type="file" class="" id="inputfile" accept="application/pdf, application/vnd.ms-excel">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputamount" class="col-sm-2 col-form-label">Amount</label>
                    <div class="col-sm-8">
                        <input type="number" class="form-control" id="inputamount">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="Textarea1" class="col-sm-2 col-form-label">Comment</label>
                    <div class="col-sm-8">
                        <textarea class="form-control" id="Textarea1" rows="3"></textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-1">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <div class="col-sm-1">
                        <button type="reset" class="btn btn-primary">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
&nbsp;{% endblock %}

newprintpress15/templates/addMsupplier.html
{% extends "base.html"%}

{%block content%}
{% load static %}
{% load bootstrap4 %}
<div class="card  mx-3 my-3">

    <div class="card-body ">
        <h4 class="card-title">New Suppliers</h4>
        <hr>
        <div class="row">
            <div class="col">

                <img src="{% static 'img/22558.jpg'%}" style="width:500px;height:430px">
            </div>
            <div class="col">
                {% if error %}
                <div class="alert alert-danger text-center" role="alert">
                    {{error}}
                </div>
                {% endif %}

                <form method="post" action="{% url 'add-Msupplier' %}" class="needs-validation"
                      onsubmit="validatepassword()" novalidate>
                    {% csrf_token %}
                    <div class="col-md-12 ">
                        <input type="text" name="name" class="form-control" id="validationCustom01"
                               placeholder="Enter the Name" required>
                        <div class="invalid-feedback">
                            Please enter the Name
                        </div>
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" name="company" class="form-control" id="validationCustom02"
                               placeholder="Enter the Company Name " required>
                        <div class="invalid-feedback">
                            Please enter the company name
                        </div>
                    </div>
                    
                                      <br>
                    <div class="col-md-12">
                        <input type="text" name="mobile" class="form-control" id="validationCustom07"
                               placeholder="Mobile No" required maxlength=10 pattern=".{10,}">
                        <div class="invalid-feedback">
                            Please provide valid mobile number
                        </div>
                    </div>
                    <br>
                    <div class="col-md-12">
                        <textarea class="form-control" type="text" placeholder="Enetr the Address" name="address"
                                  id="address" cols="3" /></textarea>
                        <div class="invalid-feedback">
                            Please enter the address
                        </div>
                    </div>
                    <br>
                    <br>

                    <div class="col-md-12">
                        <button class="btn btn-success mt-3 " type="submit">Submit</button>
                        <br><br>

                    </div>


                </form>

            </div>
        </div>
    </div>
</div>
</div>
<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();

</script>


</div>
</div>
{%endblock content%}

newprintpress15/templates/base2.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Jagdamba </title>
  </head>
  <body>
     <div class="container" >
  <div class="text-center mt-4 "  >
  <h1>Jagdamba</h1>
    <h6>Offset And Digital</h6>
    <hr>
</div>
</div>


{% block content %}

{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

newprintpress15/templates/deletenotification.html
{% extends 'base.html'%}
{% block content%}
<br>    
<div class="container">
            <div class="card">
        
            <div class="card-body">
                
                <h4>Are you sure want to delete this {{service}} {{name}}  </h4>
                <Strong>{{note}}</strong>
            </div>
            <div class="form-group col-sm-12 float-right">
            <div class="float-right">
                <a class="btn btn-danger" href="{% url func id %}">yes,i'm sure</a>
                <a class="btn btn-secondary " href="{% url 'dashboard' %}">Cancel</a>
            </div>
            </div>
        </div>
    </div>
    </div>
{% endblock content%}

newprintpress15/templates/orderForm.html
{% extends 'base.html'%}
{% block content %}
{% load bootstrap4 %}
{% load widget_tweaks %}
{% load static %}
<div class="card  mx-3 my-3">
  <div class="card-body ">
    <h4 class="card-title">Place Order</h4>
    <hr />
    <div class="row">
      <div class="col">
        <img class="img-fluid" alt="Responsive image" src="{% static 'img/22562.jpg'%}"
          style="width:500px;height:450px" />
      </div>
      <div class="col">
        <form method="post" enctype="multipart/form-data" class="needs-validation" onsubmit="validatepassword()"
          novalidate>
          {% csrf_token %}
          <div class="form-group">
            <label for="id_supplierName">Service provider</label>
            {% render_field form.supplierName class="form-control" id="id_supplierName" %}
          </div>
          <div class="form-group">
            <label for="id_OrderName">Order Name</label>
            {% render_field form.OrderName class="form-control" id="id_OrderName" %}
          </div>
          <div class="form-group">
            <label for="id_Date">Date :</label>
            {% render_field form.Date class="form-control" type="Date" name="Date" id="id_Date" %}
          </div>
          <div class="form-group">
            <label for="id_document">Attachment :</label><input type="file" name="document" class="form-control-file"
              title="" required id="id_document" multiple />
          </div>

          <div class="form-group">
            <label for="id_Size">Size</label><input type="text" name="Size" maxlength="30" class="form-control"
              placeholder="Size" title="" required id="id_Size" />
          </div>
          <div class="form-group">
            <label for="id_Date">GSM :</label>
            {% render_field form.gsm class="form-control" %}
          </div>
          <div class="form-group">
            <label for="id_Quantity">Quantity</label>
            <input type="number" name="Quantity" class="form-control" placeholder="Quantity" title="" required
              id="id_Quantity" />
          </div>
          <div class="form-group">
            <label for="id_Amount">Amount</label><input type="number" name="Amount" class="form-control"
              placeholder="Amount" title="" required id="id_Amount" />
          </div>
          <div class="form-group">
            <label for="id_Comment">Comment</label><textarea name="Comment" cols="40" rows="3" class="form-control"
              placeholder="Comment" title="" id="id_Comment"></textarea>
          </div>
          <div class="form-group">
            <input class="form-check-input ml-2 mr-4" type="checkbox" id="sendMail" name="sendMail">
            <label class=" ml-4" for="gridCheck1">
              Send Email
            </label>
          </div>
          <button type="submit" class="btn btn-success">Order Place</button>
        </form>
      </div>
    </div>
  </div>
  <script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
      "use strict";
      window.addEventListener(
        "load",
        function () {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName("needs-validation");
          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function (form) {
            form.addEventListener(
              "submit",
              function (event) {
                if (form.checkValidity() === false) {
                  event.preventDefault();
                  event.stopPropagation();
                }
                form.classList.add("was-validated");
              },
              false
            );
          });
        },
        false
      );
    })();
  </script>

  {% endblock content %}
</div>

newprintpress15/templates/updateform.html
{% extends 'base.html'%}
{% block content %}
{% load bootstrap4 %}
{% load widget_tweaks %}
{% load static %}
<div class="card  mx-3 my-3">

    <div class="card-body ">
        <h4 class="card-title">Update Service Provider Details</h4>
        <hr>
        <div class="row">
            <div class="col">

                <img src="{% static 'img/22562.jpg'%}" style="width:500px;height:450px">
            </div>
            <div class="col">

                <form method="post" novalidate>
                    {% csrf_token %}
                   
                <div class="form-group">
                <label for="id_Name">Name</label>
                    {{ form.Name|attr:"class=form-control"|attr:"type=text"|attr:"readonly" }}

                {% comment %} {% render_field form.Name class="form-control" type="text"  %} {% endcomment %}
                    </div>
                               <div class="form-group">
                <label for="id_Company">Company</label>
                 {{ form.Company|attr:"class=form-control"|attr:"type=text"|attr:"readonly" }}
                 {% comment %} {% render_field form.Company class="form-control" type="text" %} {% endcomment %}
                </div>
                <div class="form-group">
<label for="id_Email">Email</label>
 {% render_field form.Email class="form-control" type="email" %}
</div>
<div class="form-group">
<label for="id_Mobile">Mobile</label>
 {% render_field form.Mobile class="form-control" type="text" %}
</div>
<div class="form-group">
<label for="id_Address">Address</label>
 {% render_field form.Address class="form-control" rows="3" type="text" %}
</div>
                    <button type="submit" class="btn btn-success">Save Details</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock content %}